#!/bin/sh

echo "### untested - remove 'exit' on your own risk"
echo "### working for Raspbian Jessie only

echo "This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details."

exit

echo "### upgrade"
sudo apt-get update
sudo apt-get upgrade -y

echo "### install"
sudo apt-get install -y pkg-config libgl1-mesa-dev libgles2-mesa-dev \
   python-pygame python-setuptools libgstreamer1.0-dev git-core \
   gstreamer1.0 python-dev \
   fonts-droid # clock

echo "### pip"
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
sudo python get-pip.py

echo "### all pip packages ..."
sudo pip install cython pygments docutils python-forecastio pytz tzlocal

echo "### download the latest kivy and build it (will take time, have a nap)"
git clone https://github.com/kivy/kivy
cd kivy
python setup.py build

echo "### kivy install"
sudo python setup.py install
